development:
  adapter: postgresql
  encoding: unicode
  database: ouac_development
  host: localhost
  username: alexdavidow
  password:
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: oauc_test  
  host: localhost
  username: alexdavidow
  password: 
  pool: 5
