development:
  adapter: postgresql
  encoding: unicode
  database: ouac
  host: localhost
  username: alexdavidow
  password: 
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: ouac_test
  host: localhost
  username: alexdavidow
  password: 
  pool: 5
