development:
  adapter: postgresql
  database: oauc
  pool: 5
  timeout: 5000
  host: localhost
  username: frank
  password: 'password'

test:
  adapter: postgresql
  database: oauc_test
  pool: 5
  timeout: 5000
  host: localhost
  username: frank
  password: 'password'

