development:
  adapter: postgresql
  encoding: unicode
  database: ouac_development
  host: localhost
  username: alexdavidow
  pool: 5

# test: &test
test:
  adapter: postgresql
  encoding: unicode
  database: ouac_test
  host: localhost
  username: alexdavidow
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: ouac_production
  host: localhost
  username: alexdavidow
  pool: 5