development:
  adapter: postgresql
  encoding: unicode
  database: oauc
  host: localhost
  username: frank
  password: 'password'
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: oauc_test 
  host: localhost
  username: frank
  password: 'password'
  pool: 5
